services:
  squadbot:
    image: squadbot
    build:
      context: .
      dockerfile: squadbot.Dockerfile
    networks:
      - botnet
    env_file: 
      - .env
  redis:
    image: redis:7.0.2
    networks:
      botnet:
        aliases:
          - db

networks:
  botnet: